<template lang="pug">
  div
    h1 Our Privacy Policy
    p This Privacy Policy describes how webgems collects, uses and discloses information, and what choices you have with respect to the information. We respect the Browser's "Do Not Track" feature, you won't be affected by this policy if enabled.

    h2 Information We Collect
    p This website uses the web analysis service software Matomo (www.matomo.org), a service of the provider InnoCraft Ltd., 150 Willis St, 6011 Wellington, New Zealand, (“Matomo”) to collect and store data based on our legitimate interest in the statistical analysis of the user behavior for optimization and marketing purposes as per article 6(1) lit. f GDPR.
    p This data can be used to create and evaluate pseudonymized usage profiles for the same purpose. For this purpose, cookies may be used. The data collected with the Matomo technology (including its pseudonymized IP address) is processed on servers, which are hosted by Contabo GmbH.
    p Contabo GmbH does not have access to the servers nor the data that is processed (§ 6 Server-administration, Contabo's Terms & Conditions). For more information visit&nbsp;
      a.highlighted(href="https://contabo.com/agb.html") Contabo's Terms & Conditions.
    p The information generated by the cookie in the pseudonymous user profile will not be used to personally identify the visitor to this website and will not be combined with personal data about the bearer of the pseudonym.

    h2 Proccessed Data
    p The following information is processed when visiting webgems:
    ol(type="I")
      li
        strong Cookie Information.&nbsp;
        | Webgems uses cookies on this website that are necessary for Matomo's analytics. The Websites and Services we provide, do not include cookies and similar tracking technologies of third parties. For more details about how we use these technologies, please see our&nbsp;
        nuxt-link.highlighted(to="cookie-policy") Cookie Policy.
      li
        strong Log data.&nbsp;
        | As with most websites and technology services delivered over the Internet, our servers automatically collect information when you access or use our Websites or Services and record it in log files. This log data may include the Internet Protocol (IP) address, the address of the web page visited before using the Website or Services, browser type and settings, the date and time the Services were used, information about browser configuration and plugins, language preferences and cookie data.
      li
        strong Device information.&nbsp;
        | Matomo collects information about devices accessing the Services, including type of device, what operating system is used, device settings, application IDs, unique device identifiers and crash data. Whether we collect some or all of this Other Information often depends on the type of device used and its settings.
      li
        strong IP information.&nbsp;
        | Your IP address will be pseudonymized by 2 byte(s) before any further processing of your data, e.g. 192.168.xxx.xxx.
      li
        strong Location information.&nbsp;
        | Matomo uses your pseudonymized IP address in order to approximate determine your location by country.

    h2 Data Retention
    p All data that is being processed, will be automatically deleted after 180 days.

    h2 How We Disclose and Share Information
    p The analytics for this project will not be shared with third parties at any given point. Long time contributors of the project may have access to view analytics interface while not being able to alter the data itself.

    h2 Opt Out From Tracking
    p If you do not agree to this data from your visit being stored and evaluated, then you can object to the storage and use at any time by clicking below. In this case, an opt-out cookie will be placed in your browser, which means that Matomo does not collect any session data. Please note that the complete deletion of your cookies means that the opt-out cookie will be deleted too and you may need to activate it again.
    iframe(style="border: 0; width: 100%; border-radius: 3px; font-family:Poppins,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;" src="https://stats.lost.services/index.php?module=CoreAdminHome&action=optOut&language=en&backgroundColor=08e5ff&fontColor=212121&fontSize=&fontFamily=Poppins")

    h2 Re-Enable Cookie Banner
    p Click&nbsp;
      a.highlighted(@click.preventDefault="restoreCookieNotice") here!

    h2 Contact Us
    p For any data privacy related enquiries, such as requesting a copy of your information or complete deletion, please contact us via mail at&nbsp;
      a(href="mailto:dataprivacy@webgems.io") dataprivacy@webgems.io
</template>

<script>
export default {
  data() {
    return {
    }
  },
  methods: {
    restoreCookieNotice() {
      if(typeof(Storage) !== 'undefined'){
        localStorage.removeItem('cookieNoticeHidden')
        location.reload()
      }
    },
    checkCookieNoticeRestore() {
      if(typeof(Storage) !== 'undefined'){
        let cookieNotice = localStorage.getItem('cookieNoticeRestore')
        if(cookieNotice === true) {
          this.showRestore = true
          console.log('as', this.showRestore)
        } else {
          this.showRestore = false
        }
      }
    },
  },
}
</script>

<style lang="scss" scoped>
h2 {
  margin-top: 2rem;
  margin-bottom: 0.5rem;
}
p {
  margin-top: 0;
}
</style>